### ISSUE TITLE
Stuck on actionRegister

### ISSUE THREAD

**Issue by saad1056** [AnvizJacobs/AnvizCloudKit#1]
The code you provided did not work on Anviz W1.

12/12/2017 17:20:46	Debug	actionRegister: Device ID - ffad05f38cbd0e28afea7ea4f8628e2e

It keeps hitting actionRegister, Please check above log,
Further, Cloud icon in device also has exclamatory mark.

**Comment by mjankowski85** [comment]
I have similar problem with w1, but get rid of "!" on my cloud. You need to check what your server is asked for, i used tcpflow for ubuntu for it. The problem on server with PHP7.0 is because mcrypt_encrypt function from Tools returns false for $sha1 key when its length is 8 - when its 24 exclamatory mark disappears, but i think it won't working this way too ;)

Another problem is that i'm getting "soap client bad request" error from w1's actionTransport. Request data is like this: 
<ns1:actionTransport>
<serial_number>6&#x97;ihU2&#x8C;&#x96;&#x1B;&#xF;a&#x99;|</serial_number>
<data>H5BmzvcmtWMfkGbO9ya1Y0EwbkldbuZ3+VrljbbTEiT5WuWNttMSJPla5Y220xIkw+nwZ3H95M0=</data>
</ns1:actionTransport>

I'm not even sure if there should be serial_number of w1 or token which i send during actionRegister :/
I saw somewhere an info that you have to change config's KEY value on prod environment, but don't know how to get KEY from my w1 yet...

**Comment by saad1056** [comment]
So, did you get your W1 working on your cloud successfully?

**Comment by mjankowski85** [comment]
yep, but with php starting from 5.6+ you cant use mcrypt, because it gives an error
Warning:  mcrypt_encrypt(): Key of size 8 not supported by this algorithm. Only keys of size 24 supported
So this api works on php 5.4 - 5.5 ;)

**Comment by mjankowski85** [comment]
When you will change php version you have to change config KEY value too - my device uses '********' and i'm able to run any command now ;)

**Comment by saad1056** [comment]
Which version would you recommend?

**Comment by saad1056** [comment]
May I have your email address?

**Comment by mjankowski85** [comment]
mjankowski at x-one.com.pl

**Comment by saad1056** [comment]
Thanks, Check your email inbox.

**Comment by saad1056** [comment]
I cannot enroll employee into machine, further .. there is no documentation provided for this task..

How to enroll fp template as well..

**Comment by saad1056** [comment]
I am unable to

**Comment by saad1056** [comment]
I cannot enroll user as admin as well, by setting is_admin=1 ..
